DROP TABLE IF EXISTS MUSICS CASCADE;

CREATE TABLE IF NOT EXISTS MUSICS(
	ID SERIAL PRIMARY KEY,
    UUID VARCHAR(36) NOT NULL,
    MUSIC VARCHAR(10000),
    NAME VARCHAR(200),
    DESCRIPTION VARCHAR (200),
    NO_OF_LIKES INTEGER ,
    USER_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP,
    STATUS VARCHAR(26)
);

ALTER TABLE MUSICS ADD CONSTRAINT FK_MUSIC FOREIGN KEY(USER_ID) REFERENCES USERS(ID);
